### ISSUE TITLE
See - official laminas/laminas-cli

### ISSUE THREAD

**Issue by michalbundyra** [netglue/laminas-symfony-console#1]
Hey,
some time ago we have started working on official laminas-cli:
https://github.com/laminas/laminas-cli

I was writing about it more on our Slack.

Looking quickly on this library and it looks like you are trying to build the same.
I might be wrong, and maybe you have different goal here.

We would appreciate help with our official library, tho :) Thanks!

**Comment by gsteel** [comment]
Hi @michalbundyra - I only just spotted your issue - sorry for my ignorance! I'd be delighted to contribute anything you think might be useful. I'd say that the goals are nigh-on identical so I'll update the readme to point to the Laminas package as soon as possible.

Let me know if you think that there's anything in this lib that would make a worthy pull on the official package.
